-- MySQL Script generated by MySQL Workbench
-- Sun 08 Jun 2025 09:36:52 PM -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema uniformes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uniformes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uniformes` DEFAULT CHARACTER SET utf8 ;
USE `uniformes` ;

-- -----------------------------------------------------
-- Table `uniformes`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Servidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Servidor` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Servidor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45),
  `matricula` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `ativo` TINYINT NOT NULL,
  `primeiro_acesso` TINYINT NOT NULL DEFAULT 1, 
  `fk_departamento` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Servidor_Departamento1_idx` (`fk_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_Servidor_Departamento1`
    FOREIGN KEY (`fk_departamento`)
    REFERENCES `uniformes`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Curso` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `n_periodos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45),
  `telefone` VARCHAR(45),
  `matricula` VARCHAR(45) NOT NULL,
  `idade` INT,
  `periodo` INT NOT NULL,
  `fk_curso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Aluno_Curso_idx` (`fk_curso` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Curso`
    FOREIGN KEY (`fk_curso`)
    REFERENCES `uniformes`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`TipoUniforme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`TipoUniforme` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`TipoUniforme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Tamanho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Tamanho` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Tamanho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Uniforme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Uniforme` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Uniforme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `fk_tipo_uniforme` INT NOT NULL,
  `fk_tamanho` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Uniforme_TipoUniforme1_idx` (`fk_tipo_uniforme` ASC) VISIBLE,
  INDEX `fk_Uniforme_Tamanho1_idx` (`fk_tamanho` ASC) VISIBLE,
  CONSTRAINT `fk_Uniforme_TipoUniforme1`
    FOREIGN KEY (`fk_tipo_uniforme`)
    REFERENCES `uniformes`.`TipoUniforme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uniforme_Tamanho1`
    FOREIGN KEY (`fk_tamanho`)
    REFERENCES `uniformes`.`Tamanho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Entrega` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_entrega` DATE NOT NULL,
  `semestre` INT NOT NULL,
  `ano` YEAR NOT NULL,
  `trocado` TINYINT NOT NULL DEFAULT 0,
  `quantidade` INT NOT NULL,
  `fk_servidor` INT NOT NULL,
  `fk_aluno` INT,
  `fk_uniforme` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Entrega_Servidor1_idx` (`fk_servidor` ASC) VISIBLE,
  INDEX `fk_Entrega_Aluno1_idx` (`fk_aluno` ASC) VISIBLE,
  INDEX `fk_Entrega_Uniforme1_idx` (`fk_uniforme` ASC) VISIBLE,
  CONSTRAINT `fk_Entrega_Servidor1`
    FOREIGN KEY (`fk_servidor`)
    REFERENCES `uniformes`.`Servidor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrega_Aluno1`
    FOREIGN KEY (`fk_aluno`)
    REFERENCES `uniformes`.`Aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrega_Uniforme1`
    FOREIGN KEY (`fk_uniforme`)
    REFERENCES `uniformes`.`Uniforme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Troca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Troca` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Troca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_troca` DATE NOT NULL,
  `fk_entrega_antiga` INT NOT NULL,
  `fk_entrega_nova` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Troca_Entrega2_idx` (`fk_entrega_antiga` ASC) VISIBLE,
  INDEX `fk_Troca_Entrega1_idx` (`fk_entrega_nova` ASC) VISIBLE,
  CONSTRAINT `fk_Troca_Entrega2`
    FOREIGN KEY (`fk_entrega_antiga`)
    REFERENCES `uniformes`.`Entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Troca_Entrega1`
    FOREIGN KEY (`fk_entrega_nova`)
    REFERENCES `uniformes`.`Entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Fornecedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Entradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Entradas` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Entradas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_entrada` DATE NOT NULL,
  `quantidade` INT NOT NULL,
  `fk_fornecedor` INT NOT NULL,
  `fk_uniforme` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Entradas_Fornecedor1_idx` (`fk_fornecedor` ASC) VISIBLE,
  INDEX `fk_Entradas_Uniforme1_idx` (`fk_uniforme` ASC) VISIBLE,
  CONSTRAINT `fk_Entradas_Fornecedor1`
    FOREIGN KEY (`fk_fornecedor`)
    REFERENCES `uniformes`.`Fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entradas_Uniforme1`
    FOREIGN KEY (`fk_uniforme`)
    REFERENCES `uniformes`.`Uniforme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- INICIO INSERTS
INSERT INTO `uniformes`.`Tamanho` (`nome`) VALUES ('P'), ('M'), ('G'), ('GG');
INSERT INTO `uniformes`.`TipoUniforme` (`nome`) VALUES ('Camisa Branca'), ('Camisa Verde'), ('Regata Verde'), ('Calça'), ('Bermuda');
INSERT INTO `uniformes`.`Uniforme` (`quantidade`, `fk_tipo_uniforme`, `fk_tamanho`) VALUES 
	(50, 1, 1), 
	(50, 1, 2), 
	(50, 1, 3), 
	(50, 1, 4), 
	(50, 2, 1), 
	(50, 2, 2), 
	(50, 2, 3), 
	(50, 2, 4), 
	(50, 3, 1), 
	(50, 3, 2), 
	(50, 3, 3), 
	(50, 3, 4), 
	(50, 4, 1), 
	(50, 4, 2), 
	(50, 4, 3), 
	(50, 4, 4), 
	(50, 5, 1), 
	(50, 5, 2), 
	(50, 5, 3), 
	(50, 5, 4);
INSERT INTO `uniformes`.`Departamento` (`nome`) VALUES ('DEPAE'), ('DAPE'), ('DG');
INSERT INTO `uniformes`.`Curso` (`nome`, `n_periodos`) VALUES ('Química', '3'), ('Eletrotécnica', '3'), ('Informática', '3'), ('Edificações', '3');
INSERT INTO `uniformes`.`Fornecedor` (`nome`) VALUES ('Uniformes LTDA'), ('Confecção & Uniformes'), ('Uniformes & Cia LTDA');
INSERT INTO `uniformes`.`Servidor` (`nome`, `sobrenome`, `email`, `telefone`, `matricula`, `senha`, `ativo`, `primeiro_acesso`, `fk_departamento`) VALUES 
	('Admin', 'Sistema', 'admin@sistema.com', '00000000000', 'admin01', '$2a$12$BZfrVc0ENzsPz2TJq6h4fOivZaMlLUE0DTulOXM6wgOYTa/pnh6oi', 1, 0, 1), 
	('Willians', 'de Paula', 'willians.paula@ifro.edu.br', '69981112233', '100000', '$2a$12$BHVMvvoBbbUlexG1wbIk/u9sw7Csoiy9KrTxAuiEjWLGnf1WaQkGi', 1, 1, 3), 
	('Beatriz', 'Mendes', 'beatriz.mendes@ifro.edu.br', '69981223733', '100001', '$2a$12$3f8tL8gx4mtJdDTFfuDnbOx52ODIHm7aNY/apwOE7v69i6PF/PcYe', 1, 1, 1),
	('Carlos', 'Eduardo', 'carlos.eduardo@ifro.edu.br', '69981153273', '100002', '$2a$12$..TdosVye3aySPIOMo4u5usuF1qmLK6aPjTmRsF4X63GCwzBZ4S8a', 1, 1, 1);
INSERT INTO `uniformes`.`Aluno` (`nome`, `sobrenome`, `email`, `telefone`, `matricula`, `idade`, `periodo`, `fk_curso`) VALUES
	('Ana', 'Oliveira', 'ana.oliveira@email.com', '991234501', '2024106090025', 21, 1, 1),
	('Bruno', 'Costa', 'bruno.costa@email.com', '991234502', '2024106090026', 19, 1, 2),
	('Carla', 'Santos', 'carla.santos@email.com', '991234503', '2024106090027', 22, 1, 3),
	('Daniel', 'Pereira', 'daniel.pereira@email.com', '991234504', '2024106090028', 20, 2, 4),
	('Eduarda', 'Ferreira', 'eduarda.ferreira@email.com', '991234505', '2024106090029', 23, 3, 1),
	('Felipe', 'Almeida', 'felipe.almeida@email.com', '991234506', '2024106090030', 18, 3, 2),
	('Gabriela', 'Rodrigues', 'gabriela.rodrigues@email.com', '991234507', '2024106090031', 25, 2, 3),
	('Heitor', 'Martins', 'heitor.martins@email.com', '991234508', '2024106090032', 20, 1, 4),
	('Isabela', 'Gomes', 'isabela.gomes@email.com', '991234509', '2024106090033', 19, 3, 1),
	('Juliano', 'Ribeiro', 'juliano.ribeiro@email.com', '991234510', '2024106090034', 24, 2, 2),
	('Larissa', 'Carvalho', 'larissa.carvalho@email.com', '991234511', '2024106090035', 21, 3, 3),
	('Marcos', 'Gonçalves', 'marcos.goncalves@email.com', '991234512', '2024106090036', 22, 1, 4),
	('Natália', 'Lopes', 'natalia.lopes@email.com', '991234513', '2024106090037', 20, 2, 1),
	('Otávio', 'Mendes', 'otavio.mendes@email.com', '991234514', '2024106090038', 26, 1, 2),
	('Patrícia', 'Nunes', 'patricia.nunes@email.com', '991234515', '2024106090039', 19, 1, 3),
	('Rafael', 'Teixeira', 'rafael.teixeira@email.com', '991234516', '2024106090040', 21, 3, 4),
	('Sofia', 'Correia', 'sofia.correia@email.com', '991234517', '2024106090041', 23, 1, 1),
	('Tiago', 'Barros', 'tiago.barros@email.com', '991234518', '2024106090042', 20, 2, 2),
	('Valentina', 'Moraes', 'valentina.moraes@email.com', '991234519', '2024106090043', 22, 2, 3),
	('Vinícius', 'Pinto', 'vinicius.pinto@email.com', '991234520', '2024106090044', 18, 3, 4),
	('Yasmin', 'Castro', 'yasmin.castro@email.com', '991234521', '2024106090045', 24, 2, 1),
	('Alex', 'Dias', 'alex.dias@email.com', '991234522', '2024106090046', 21, 1, 2),
	('Beatriz', 'Fernandes', 'beatriz.fernandes@email.com', '991234523', '2024106090047', 20, 2, 3),
	('Caio', 'Lima', 'caio.lima@email.com', '991234524', '2024106090048', 19, 3, 4),
	('Débora', 'Souza', 'debora.souza@email.com', '991234525', '2024106090049', 25, 1, 1),
	('Elias', 'Monteiro', 'elias.monteiro@email.com', '991234526', '2024106090050', 22, 2, 2),
	('Flávia', 'Azevedo', 'flavia.azevedo@email.com', '991234527', '2024106090051', 20, 3, 3),
	('Guilherme', 'Barbosa', 'guilherme.barbosa@email.com', '991234528', '2024106090052', 23, 3, 4),
	('Helena', 'Cardoso', 'helena.cardoso@email.com', '991234529', '2024106090053', 18, 1, 1),
	('Igor', 'Duarte', 'igor.duarte@email.com', '991234530', '2024106090054', 21, 3, 2),
	('Júlia', 'Freitas', 'julia.freitas@email.com', '991234531', '2024106090055', 26, 2, 3),
	('Leonardo', 'Vieira', 'leonardo.vieira@email.com', '991234532', '2024106090056', 20, 2, 4),
	('Manuela', 'Santana', 'manuela.santana@email.com', '991234533', '2024106090057', 19, 1, 1),
	('Nicolas', 'Machado', 'nicolas.machado@email.com', '991234534', '2024106090058', 22, 1, 2),
	('Olívia', 'Campos', 'olivia.campos@email.com', '991234535', '2024106090059', 24, 3, 3),
	('Pedro', 'Henrique', 'pedro.henrique@email.com', '991234536', '2024106090060', 21, 3, 4),
	('Quintino', 'Neves', 'quintino.neves@email.com', '991234537', '2024106090061', 23, 2, 1),
	('Rebeca', 'Cunha', 'rebeca.cunha@email.com', '991234538', '2024106090062', 20, 2, 2),
	('Samuel', 'Ramos', 'samuel.ramos@email.com', '991234539', '2024106090063', 19, 1, 3),
	('Tatiana', 'Vargas', 'tatiana.vargas@email.com', '991234540', '2024106090064', 25, 2, 4),
	('Ulisses', 'Melo', 'ulisses.melo@email.com', '991234541', '2024106090065', 22, 3, 1),
	('Vitória', 'Rezende', 'vitoria.rezende@email.com', '991234542', '2024106090066', 20, 3, 2),
	('William', 'Siqueira', 'william.siqueira@email.com', '991234543', '2024106090067', 23, 1, 3),
	('Xavier', 'Tavares', 'xavier.tavares@email.com', '991234544', '2024106090068', 18, 1, 4),
	('Yago', 'Chaves', 'yago.chaves@email.com', '991234545', '2024106090069', 21, 3, 1),
	('Zoe', 'Borges', 'zoe.borges@email.com', '991234546', '2024106090070', 26, 2, 2),
	('Aluno', 'Extra Um', 'aluno.extra1@email.com', '991234547', '2024106090071', 20, 3, 3),
	('Aluna', 'Extra Dois', 'aluna.extra2@email.com', '991234548', '2024106090072', 19, 1, 4),
	('Estudante', 'Teste Um', 'estudante.teste1@email.com', '991234549', '2024106090073', 22, 1, 1),
	('Estudante', 'Teste Dois', 'estudante.teste2@email.com', '991234550', '2024106090074', 24, 1, 2);
INSERT INTO `uniformes`.`Entrega` (`data_entrega`, `semestre`, `ano`, `trocado`, `quantidade`, `fk_servidor`, `fk_aluno`, `fk_uniforme`) VALUES
	('2025-05-10', 3, 2025, 0, 1, 4, 1, 2), 
	('2025-05-12', 3, 2025, 0, 2, 3, 3, 5), 
	('2025-05-23', 1, 2025, 0, 2, 4, 5, 3), 
	('2025-05-30', 3, 2025, 0, 1, 3, 6, 2), 
	('2025-05-30', 1, 2025, 0, 1, 3, 2, 1), 
	('2025-06-10', 1, 2025, 0, 3, 3, 9, 6), 
	('2025-06-10', 1, 2025, 0, 1, 4, 12, 2), 
	('2025-06-12', 3, 2025, 0, 2, 3, 10, 5), 
	('2025-06-14', 1, 2025, 0, 2, 4, 5, 3), 
	('2025-06-17', 3, 2025, 0, 1, 3, 7, 2), 
	('2025-06-18', 1, 2025, 0, 1, 3, 13, 1), 
	('2025-06-23', 1, 2025, 0, 1, 3, 22, 6), 
	('2025-06-24', 1, 2025, 0, 2, 4, 10, 2), 
	('2025-06-24', 3, 2025, 0, 2, 3, 3, 5), 
	('2025-06-25', 1, 2025, 0, 2, 4, 5, 3), 
	('2025-06-25', 3, 2025, 0, 1, 3, 11, 2), 
	('2025-06-25', 1, 2025, 0, 1, 3, 15, 1), 
	('2025-06-28', 3, 2025, 0, 2, 3, 4, 6), 
	('2025-07-01', 3, 2025, 0, 1, 4, 16, 2), 
	('2025-07-05', 3, 2025, 0, 2, 3, 17, 5), 
	('2025-07-05', 1, 2025, 0, 2, 4, 15, 3), 
	('2025-07-07', 3, 2025, 0, 1, 3, 18, 2), 
	('2025-07-10', 1, 2025, 0, 2, 3, 19, 1), 
	('2025-07-10', 1, 2025, 0, 3, 3, 20, 6);

-- FIM INSERTS

-- INICIO TRIGGERS
DROP TRIGGER IF EXISTS Tgr_Insert_Troca;
DROP TRIGGER IF EXISTS Tgr_Insert_Entrada;
DROP TRIGGER IF EXISTS Tgr_Insert_Entrega;

DELIMITER //
-- Ao cadastrar entrega, subtrair de uniformes a quantidade da entrega.
CREATE TRIGGER Tgr_Insert_Entrega BEFORE INSERT
ON Entrega
FOR EACH ROW 
BEGIN
	UPDATE Uniforme AS u
    SET u.quantidade = u.quantidade - NEW.quantidade
	WHERE u.id = NEW.fk_uniforme;
END;
//
-- Ao cadastrar entrada, adicionar em uniformes a quantidade da entrada.
CREATE TRIGGER Tgr_Insert_Entrada AFTER INSERT
ON Entradas 
FOR EACH ROW
BEGIN 
	UPDATE Uniforme AS u
    SET u.quantidade = u.quantidade + NEW.quantidade
    WHERE u.id = NEW.fk_uniforme;
END;
//
-- Ao cadastrar troca, adicionar em uniformes a quantidade da entrega antiga.
CREATE TRIGGER Tgr_Insert_Troca AFTER INSERT
ON Troca
FOR EACH ROW
BEGIN
	UPDATE Uniforme AS u
    SET u.quantidade = u.quantidade + (SELECT e.quantidade FROM Entrega AS e WHERE e.id = NEW.fk_entrega_antiga)
    WHERE u.id = (SELECT e.fk_uniforme FROM Entrega AS e WHERE e.id = NEW.fk_entrega_antiga);
    
    UPDATE Entrega AS e
    SET e.trocado = 1
    WHERE e.id = NEW.fk_entrega_antiga;
END;
//
DELIMITER ;
-- FIM TRIGGERS

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
