package com.mycompany.gerenciamento.uniformes.View;

import com.mycompany.gerenciamento.uniformes.AuthController;
import com.mycompany.gerenciamento.uniformes.DAO.EntregaDAO;
import com.mycompany.gerenciamento.uniformes.Models.EntregaModel;
import com.mycompany.gerenciamento.uniformes.TableModels.EntregaTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * @author barbara
 */

public class ViewsSistema extends javax.swing.JFrame {
    private final CardLayout mainCardLayout;
    private final CardLayout authCardLayout;
    private final CardLayout appCardLayout;
    private final EntregaTableModel entregaTableModel; // Declara a tableModel
    private final AuthController authController;
    private String matriculaUpdate;
    
    public ViewsSistema() {
        initComponents();
        this.appCardLayout = (CardLayout) panel_telaInicial.getLayout();
        this.mainCardLayout = (CardLayout) main_container.getLayout();
        this.authCardLayout = (CardLayout) panel_autenticacao.getLayout();
        this.authController = new AuthController();
        
        this.entregaTableModel = new EntregaTableModel(new ArrayList<>()); //Cria modelo com uma lista vazia
        this.jTable1.setModel(entregaTableModel); //Conecta o Jtable ao criado pelo netbeans
        
        System.out.println("Painéis disponíveis:");
        for (Component comp : panel_telaInicial.getComponents()) {
            System.out.println("- " + comp.getName() + " (" + comp.getClass().getSimpleName() + ")");
        }
        
        mainCardLayout.show(main_container, "card_autenticacao");
        authCardLayout.show(panel_autenticacao, "card_login");
    }
    
    private void carregaDadosDistribuicao() {
        try {
            EntregaDAO dao = new EntregaDAO();
            List<EntregaModel> listaDeEntregas = dao.listarTodos();
            
            entregaTableModel.setEntregas(listaDeEntregas);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar os dados de distribuição.", "Erro", JOptionPane.ERROR_MESSAGE);
            error.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_container = new javax.swing.JPanel();
        panel_aplicacao = new javax.swing.JPanel();
        panel_navbar = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 80), new java.awt.Dimension(25, 800));
        jLabel7 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 80), new java.awt.Dimension(100, 800));
        nome_sistema = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 80), new java.awt.Dimension(450, 800));
        btn_nav_Inicio = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 80), new java.awt.Dimension(20, 800));
        btn_nav_distribuicao = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 80), new java.awt.Dimension(10, 800));
        btn_nav_alunos = new javax.swing.JButton();
        btn_nav_servidores = new javax.swing.JButton();
        btn_nav_uniformes = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 80), new java.awt.Dimension(20, 800));
        panel_telaInicial = new javax.swing.JPanel();
        Inicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Distribuicao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Alunos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Servidores = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Uniformes = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        subtitulo = new javax.swing.JLabel();
        tx_pesquisa = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jcb_filtros = new javax.swing.JComboBox<>();
        btn_Add_Uniforme = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_uniformes = new javax.swing.JTable();
        btn_editar = new javax.swing.JButton();
        panel_autenticacao = new javax.swing.JPanel();
        panel_login = new javax.swing.JPanel();
        lb_login_pl = new javax.swing.JLabel();
        lb_matricula_pl = new javax.swing.JLabel();
        lb_senha_pl = new javax.swing.JLabel();
        input_matricula_pl = new javax.swing.JTextField();
        input_senha_pl = new javax.swing.JPasswordField();
        btn_login_pl = new javax.swing.JButton();
        panel_primeiro_acesso = new javax.swing.JPanel();
        lb_redefinir_senha_ppa = new javax.swing.JLabel();
        lb_senha_ppa = new javax.swing.JLabel();
        lb_confirmar_senha_ppa = new javax.swing.JLabel();
        input_senha_ppa = new javax.swing.JPasswordField();
        input_confirmar_senha_ppa = new javax.swing.JPasswordField();
        btn_salvar_ppa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GERENCIAMENTO DE UNIFORMES ACADÊMICOS");
        setMaximumSize(new java.awt.Dimension(1360, 2147483647));
        setName("FrameServidores"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1360, 760));
        setSize(new java.awt.Dimension(1360, 750));

        main_container.setMaximumSize(new java.awt.Dimension(1360, 2147483647));
        main_container.setPreferredSize(new java.awt.Dimension(1360, 760));
        main_container.setLayout(new java.awt.CardLayout());

        panel_aplicacao.setMaximumSize(new java.awt.Dimension(1360, 2147483647));
        panel_aplicacao.setPreferredSize(new java.awt.Dimension(1360, 760));
        panel_aplicacao.setLayout(new java.awt.BorderLayout());

        panel_navbar.setBackground(new java.awt.Color(35, 91, 88));
        panel_navbar.setMaximumSize(new java.awt.Dimension(1360, 800));
        panel_navbar.setMinimumSize(new java.awt.Dimension(1360, 64));
        panel_navbar.setPreferredSize(new java.awt.Dimension(1360, 80));
        panel_navbar.setLayout(new javax.swing.BoxLayout(panel_navbar, javax.swing.BoxLayout.LINE_AXIS));
        panel_navbar.add(filler4);

        jLabel7.setIcon(new javax.swing.ImageIcon("src\\main\\java\\com\\mycompany\\gerenciamento\\uniformes\\Images\\logo-IFRO-PNG-branco.png"));
        panel_navbar.add(jLabel7);
        panel_navbar.add(filler1);

        nome_sistema.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nome_sistema.setForeground(new java.awt.Color(255, 255, 255));
        nome_sistema.setText("GERENCIAMENTO DE UNIFORMES ACADÊMICOS");
        panel_navbar.add(nome_sistema);
        panel_navbar.add(filler3);

        btn_nav_Inicio.setBackground(new java.awt.Color(35, 91, 88));
        btn_nav_Inicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nav_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        btn_nav_Inicio.setText("Inicio");
        btn_nav_Inicio.setBorder(null);
        btn_nav_Inicio.setBorderPainted(false);
        btn_nav_Inicio.setContentAreaFilled(false);
        btn_nav_Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nav_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nav_InicioActionPerformed(evt);
            }
        });
        panel_navbar.add(btn_nav_Inicio);
        panel_navbar.add(filler6);

        btn_nav_distribuicao.setBackground(new java.awt.Color(35, 91, 88));
        btn_nav_distribuicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nav_distribuicao.setForeground(new java.awt.Color(255, 255, 255));
        btn_nav_distribuicao.setText("Distribuição");
        btn_nav_distribuicao.setBorder(null);
        btn_nav_distribuicao.setBorderPainted(false);
        btn_nav_distribuicao.setContentAreaFilled(false);
        btn_nav_distribuicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nav_distribuicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nav_distribuicaoActionPerformed(evt);
            }
        });
        panel_navbar.add(btn_nav_distribuicao);
        panel_navbar.add(filler7);

        btn_nav_alunos.setBackground(new java.awt.Color(35, 91, 88));
        btn_nav_alunos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nav_alunos.setForeground(new java.awt.Color(255, 255, 255));
        btn_nav_alunos.setText("Alunos");
        btn_nav_alunos.setBorderPainted(false);
        btn_nav_alunos.setContentAreaFilled(false);
        btn_nav_alunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nav_alunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nav_alunosActionPerformed(evt);
            }
        });
        panel_navbar.add(btn_nav_alunos);

        btn_nav_servidores.setBackground(new java.awt.Color(35, 91, 88));
        btn_nav_servidores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nav_servidores.setForeground(new java.awt.Color(255, 255, 255));
        btn_nav_servidores.setText("Servidores");
        btn_nav_servidores.setBorderPainted(false);
        btn_nav_servidores.setContentAreaFilled(false);
        btn_nav_servidores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nav_servidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nav_servidoresActionPerformed(evt);
            }
        });
        panel_navbar.add(btn_nav_servidores);

        btn_nav_uniformes.setBackground(new java.awt.Color(35, 91, 88));
        btn_nav_uniformes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nav_uniformes.setForeground(new java.awt.Color(255, 255, 255));
        btn_nav_uniformes.setText("Uniformes");
        btn_nav_uniformes.setBorderPainted(false);
        btn_nav_uniformes.setContentAreaFilled(false);
        btn_nav_uniformes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nav_uniformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nav_uniformesActionPerformed(evt);
            }
        });
        panel_navbar.add(btn_nav_uniformes);
        panel_navbar.add(filler5);

        panel_aplicacao.add(panel_navbar, java.awt.BorderLayout.NORTH);

        panel_telaInicial.setBackground(new java.awt.Color(204, 255, 102));
        panel_telaInicial.setMaximumSize(new java.awt.Dimension(1360, 760));
        panel_telaInicial.setPreferredSize(new java.awt.Dimension(1360, 650));
        panel_telaInicial.setLayout(new java.awt.CardLayout());

        Inicio.setBackground(new java.awt.Color(204, 255, 153));
        Inicio.setMaximumSize(new java.awt.Dimension(1360, 760));
        Inicio.setMinimumSize(new java.awt.Dimension(1360, 714));
        Inicio.setPreferredSize(new java.awt.Dimension(1360, 760));

        jLabel1.setText("Inicio");

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_telaInicial.add(Inicio, "inicio");

        Distribuicao.setBackground(new java.awt.Color(255, 255, 255));
        Distribuicao.setMaximumSize(new java.awt.Dimension(1360, 650));
        Distribuicao.setMinimumSize(new java.awt.Dimension(1360, 650));
        Distribuicao.setPreferredSize(new java.awt.Dimension(1360, 650));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Tamanho", "Uniforme", "Matrícula", "Servidor Responsável", "Quantidade", "Data de Troca", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(4, 120, 87));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("+ Cadastrar Distribuição");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel6.setText("Controle de Distribuição");

        jLabel8.setText("Tenha controle em tempo real das distribuições de uniformes.");

        javax.swing.GroupLayout DistribuicaoLayout = new javax.swing.GroupLayout(Distribuicao);
        Distribuicao.setLayout(DistribuicaoLayout);
        DistribuicaoLayout.setHorizontalGroup(
            DistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DistribuicaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(2011, 2011, 2011))
            .addGroup(DistribuicaoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(DistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(DistribuicaoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(665, 665, 665)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DistribuicaoLayout.setVerticalGroup(
            DistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DistribuicaoLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(DistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DistribuicaoLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(42, 42, 42))
        );

        panel_telaInicial.add(Distribuicao, "distribuicao");

        Alunos.setBackground(new java.awt.Color(255, 204, 255));

        jLabel3.setText("Alunos");

        javax.swing.GroupLayout AlunosLayout = new javax.swing.GroupLayout(Alunos);
        Alunos.setLayout(AlunosLayout);
        AlunosLayout.setHorizontalGroup(
            AlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlunosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(630, 630, 630))
        );
        AlunosLayout.setVerticalGroup(
            AlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlunosLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_telaInicial.add(Alunos, "alunos");

        Servidores.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setText("Servidores");

        javax.swing.GroupLayout ServidoresLayout = new javax.swing.GroupLayout(Servidores);
        Servidores.setLayout(ServidoresLayout);
        ServidoresLayout.setHorizontalGroup(
            ServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServidoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(630, 630, 630))
        );
        ServidoresLayout.setVerticalGroup(
            ServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServidoresLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_telaInicial.add(Servidores, "servidores");

        Uniformes.setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Titulo.setText("Controle de Uniformes");

        subtitulo.setForeground(new java.awt.Color(0, 102, 102));
        subtitulo.setText("Tenha um controle em tempo real do estoque de uniformes");

        tx_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_pesquisaActionPerformed(evt);
            }
        });

        btn_buscar.setText("BUSCAR");

        jcb_filtros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camisa", "Calça", "Bermuda", "Tamanho P", "Tamanho M", "Tamanho G" }));
        jcb_filtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_filtrosActionPerformed(evt);
            }
        });

        btn_Add_Uniforme.setBackground(new java.awt.Color(0, 153, 102));
        btn_Add_Uniforme.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add_Uniforme.setText("+ Adicionar Uniforme");

        tabela_uniformes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Status", "Entrada", "Saída", "Tamanho", "Data Entrega"
            }
        ));
        jScrollPane2.setViewportView(tabela_uniformes);

        btn_editar.setText("EDITAR");

        javax.swing.GroupLayout UniformesLayout = new javax.swing.GroupLayout(Uniformes);
        Uniformes.setLayout(UniformesLayout);
        UniformesLayout.setHorizontalGroup(
            UniformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UniformesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(UniformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UniformesLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(1984, Short.MAX_VALUE))
                    .addGroup(UniformesLayout.createSequentialGroup()
                        .addGroup(UniformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(UniformesLayout.createSequentialGroup()
                                .addComponent(btn_buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tx_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jcb_filtros, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_editar))
                            .addGroup(UniformesLayout.createSequentialGroup()
                                .addGroup(UniformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subtitulo)
                                    .addComponent(Titulo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Add_Uniforme)))
                        .addGap(35, 35, 35))))
        );
        UniformesLayout.setVerticalGroup(
            UniformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UniformesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(UniformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UniformesLayout.createSequentialGroup()
                        .addComponent(Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtitulo))
                    .addComponent(btn_Add_Uniforme))
                .addGap(52, 52, 52)
                .addGroup(UniformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editar)
                    .addComponent(btn_buscar)
                    .addComponent(tx_pesquisa)
                    .addComponent(jcb_filtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        panel_telaInicial.add(Uniformes, "uniformes");

        panel_aplicacao.add(panel_telaInicial, java.awt.BorderLayout.CENTER);

        main_container.add(panel_aplicacao, "card_aplicacao");

        panel_autenticacao.setMaximumSize(new java.awt.Dimension(1360, 760));
        panel_autenticacao.setMinimumSize(new java.awt.Dimension(1360, 760));
        panel_autenticacao.setPreferredSize(new java.awt.Dimension(1360, 760));
        panel_autenticacao.setLayout(new java.awt.CardLayout());

        panel_login.setBackground(new java.awt.Color(35, 91, 88));
        panel_login.setMaximumSize(new java.awt.Dimension(1360, 760));
        panel_login.setMinimumSize(new java.awt.Dimension(1360, 760));
        panel_login.setPreferredSize(new java.awt.Dimension(1360, 760));

        lb_login_pl.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lb_login_pl.setText("LOGIN");

        lb_matricula_pl.setLabelFor(input_matricula_pl);
        lb_matricula_pl.setText("Matricula");

        lb_senha_pl.setLabelFor(input_senha_pl);
        lb_senha_pl.setText("Senha");

        input_matricula_pl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_matricula_plActionPerformed(evt);
            }
        });

        btn_login_pl.setText("login");
        btn_login_pl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_plActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_login_pl)
                    .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(input_matricula_pl, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addComponent(input_senha_pl)
                        .addComponent(lb_senha_pl)
                        .addComponent(lb_matricula_pl))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lb_login_pl)))
                .addContainerGap(1066, Short.MAX_VALUE))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lb_login_pl)
                .addGap(18, 18, 18)
                .addComponent(lb_matricula_pl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_matricula_pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_senha_pl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_senha_pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_login_pl)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        panel_autenticacao.add(panel_login, "card_login");

        panel_primeiro_acesso.setBackground(new java.awt.Color(35, 91, 88));
        panel_primeiro_acesso.setMaximumSize(new java.awt.Dimension(1360, 760));
        panel_primeiro_acesso.setMinimumSize(new java.awt.Dimension(1360, 760));

        lb_redefinir_senha_ppa.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lb_redefinir_senha_ppa.setText("REDEFINIR SENHA");

        lb_senha_ppa.setLabelFor(input_senha_ppa);
        lb_senha_ppa.setText("Senha");

        lb_confirmar_senha_ppa.setLabelFor(input_confirmar_senha_ppa);
        lb_confirmar_senha_ppa.setText("Confirmar Senha");

        btn_salvar_ppa.setText("Salvar");
        btn_salvar_ppa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_ppaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_primeiro_acessoLayout = new javax.swing.GroupLayout(panel_primeiro_acesso);
        panel_primeiro_acesso.setLayout(panel_primeiro_acessoLayout);
        panel_primeiro_acessoLayout.setHorizontalGroup(
            panel_primeiro_acessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_primeiro_acessoLayout.createSequentialGroup()
                .addGroup(panel_primeiro_acessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_primeiro_acessoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(panel_primeiro_acessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_salvar_ppa)
                            .addGroup(panel_primeiro_acessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(input_confirmar_senha_ppa, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(input_senha_ppa, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(lb_confirmar_senha_ppa)
                                .addComponent(lb_senha_ppa))))
                    .addGroup(panel_primeiro_acessoLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lb_redefinir_senha_ppa)))
                .addContainerGap(3004, Short.MAX_VALUE))
        );
        panel_primeiro_acessoLayout.setVerticalGroup(
            panel_primeiro_acessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_primeiro_acessoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lb_redefinir_senha_ppa)
                .addGap(24, 24, 24)
                .addComponent(lb_senha_ppa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_senha_ppa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_confirmar_senha_ppa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_confirmar_senha_ppa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_salvar_ppa)
                .addContainerGap(530, Short.MAX_VALUE))
        );

        panel_autenticacao.add(panel_primeiro_acesso, "card_primeiro_acesso");

        main_container.add(panel_autenticacao, "card_autenticacao");

        getContentPane().add(main_container, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nav_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nav_InicioActionPerformed
        // TODO add your handling code here:
        appCardLayout.show(panel_telaInicial, "inicio");
        System.out.println("Mostrando painel Inicio");
    }//GEN-LAST:event_btn_nav_InicioActionPerformed

    private void btn_nav_distribuicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nav_distribuicaoActionPerformed
        // TODO add your handling code here:
        carregaDadosDistribuicao();
        appCardLayout.show(panel_telaInicial, "distribuicao");
        System.out.println("Mostrando painel Distribuicao");
    }//GEN-LAST:event_btn_nav_distribuicaoActionPerformed

    private void btn_nav_alunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nav_alunosActionPerformed
        // TODO add your handling code here:
        appCardLayout.show(panel_telaInicial, "alunos");
        System.out.println("Mostrando painel Alunos");
        //JOptionPane.showMessageDialog(this, "Painel de Alunos ainda não implementado");
    }//GEN-LAST:event_btn_nav_alunosActionPerformed

    private void btn_nav_servidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nav_servidoresActionPerformed
        // TODO add your handling code here:
        appCardLayout.show(panel_telaInicial, "servidores");
        System.out.println("Mostrando painel Servidores");
        //JOptionPane.showMessageDialog(this, "Painel de Servidores ainda não implementado");
    }//GEN-LAST:event_btn_nav_servidoresActionPerformed

    private void btn_nav_uniformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nav_uniformesActionPerformed
        // TODO add your handling code here:
        appCardLayout.show(panel_telaInicial, "uniformes");
        System.out.println("Mostrando painel Uniformes");
        //JOptionPane.showMessageDialog(this, "Painel de Uniformes ainda não implementado");
    }//GEN-LAST:event_btn_nav_uniformesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void input_matricula_plActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_matricula_plActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_matricula_plActionPerformed

    private void btn_login_plActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_plActionPerformed
        String matriculaLogin = input_matricula_pl.getText();
        String senhaLogin = new String(input_senha_pl.getPassword());

        String login = this.authController.autenticar(matriculaLogin, senhaLogin);
        
        input_senha_pl.setText("");
        
        switch (login) {
            case "autenticado":
                mainCardLayout.show(main_container, "card_aplicacao");
                input_matricula_pl.setText("");
                JOptionPane.showMessageDialog(this, "Login efetuado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                break;
            case "p_acesso":
                this.matriculaUpdate = matriculaLogin;
                authCardLayout.show(panel_autenticacao, "card_primeiro_acesso");
                JOptionPane.showMessageDialog(this, "Identificamos que esse é seu primeiro acesso ao sistema, por favor, altere sua senha!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                break;
            case "n_autenticado":
                JOptionPane.showMessageDialog(this, "Matrícula ou senha inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }//GEN-LAST:event_btn_login_plActionPerformed

    private void btn_salvar_ppaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_ppaActionPerformed
        String senhaUpdate = new String(input_senha_ppa.getPassword());
        String senhaUpdateConf = new String(input_confirmar_senha_ppa.getPassword());
        
        if (senhaUpdate.equals(senhaUpdateConf)) {
            boolean confirm = this.authController.redefinirSenha(this.matriculaUpdate, senhaUpdate);
            if (confirm) {
                this.matriculaUpdate = null;
                authCardLayout.show(panel_autenticacao, "card_login");
                input_senha_ppa.setText("");
                input_confirmar_senha_ppa.setText("");
                JOptionPane.showMessageDialog(this, "Senha alterada com sucesso!\nEfetue o login", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao redefinir a senha!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "As senhas não são iguais!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_salvar_ppaActionPerformed

    private void tx_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_pesquisaActionPerformed

    private void jcb_filtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_filtrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_filtrosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alunos;
    private javax.swing.JPanel Distribuicao;
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel Servidores;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel Uniformes;
    private javax.swing.JButton btn_Add_Uniforme;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_login_pl;
    private javax.swing.JButton btn_nav_Inicio;
    private javax.swing.JButton btn_nav_alunos;
    private javax.swing.JButton btn_nav_distribuicao;
    private javax.swing.JButton btn_nav_servidores;
    private javax.swing.JButton btn_nav_uniformes;
    private javax.swing.JButton btn_salvar_ppa;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JPasswordField input_confirmar_senha_ppa;
    private javax.swing.JTextField input_matricula_pl;
    private javax.swing.JPasswordField input_senha_pl;
    private javax.swing.JPasswordField input_senha_ppa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcb_filtros;
    private javax.swing.JLabel lb_confirmar_senha_ppa;
    private javax.swing.JLabel lb_login_pl;
    private javax.swing.JLabel lb_matricula_pl;
    private javax.swing.JLabel lb_redefinir_senha_ppa;
    private javax.swing.JLabel lb_senha_pl;
    private javax.swing.JLabel lb_senha_ppa;
    private javax.swing.JPanel main_container;
    private javax.swing.JLabel nome_sistema;
    private javax.swing.JPanel panel_aplicacao;
    private javax.swing.JPanel panel_autenticacao;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel panel_navbar;
    private javax.swing.JPanel panel_primeiro_acesso;
    private javax.swing.JPanel panel_telaInicial;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JTable tabela_uniformes;
    private javax.swing.JTextField tx_pesquisa;
    // End of variables declaration//GEN-END:variables
}
