package com.mycompany.gerenciamento.uniformes.View;

import com.mycompany.gerenciamento.uniformes.AuthController;
import java.awt.*;

/**
 * @author barbara
 */

public class ViewsSistema extends javax.swing.JFrame {
    private CardLayout cardLayout;
    
    public ViewsSistema() {
        initComponents();
        System.out.println("Painéis disponíveis:");
        for (Component comp : panel_telaInicial.getComponents()) {
            System.out.println("- " + comp.getName() + " (" + comp.getClass().getSimpleName() + ")");
        }
        cardLayout = (CardLayout) panel_telaInicial.getLayout();
        cardLayout.show(panel_telaInicial, "Inicio");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_navbar = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 80), new java.awt.Dimension(25, 800));
        jLabel7 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 80), new java.awt.Dimension(100, 800));
        nome_sistema = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 80), new java.awt.Dimension(450, 800));
        btn_nav_Inicio = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 80), new java.awt.Dimension(20, 800));
        btn_nav_distribuicao = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 80), new java.awt.Dimension(10, 800));
        btn_nav_alunos = new javax.swing.JButton();
        btn_nav_servidores = new javax.swing.JButton();
        btn_nav_uniformes = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 80), new java.awt.Dimension(20, 800));
        panel_telaInicial = new javax.swing.JPanel();
        Inicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Distribuicao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Alunos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Servidores = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Uniformes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GERENCIAMENTO DE UNIFORMES ACADÊMICOS");
        setMaximumSize(new java.awt.Dimension(1360, 2147483647));
        setName("FrameServidores"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1360, 760));
        setSize(new java.awt.Dimension(1360, 750));

        panel_navbar.setBackground(new java.awt.Color(35, 91, 88));
        panel_navbar.setMaximumSize(new java.awt.Dimension(1360, 800));
        panel_navbar.setMinimumSize(new java.awt.Dimension(1360, 64));
        panel_navbar.setPreferredSize(new java.awt.Dimension(1360, 80));
        panel_navbar.setLayout(new javax.swing.BoxLayout(panel_navbar, javax.swing.BoxLayout.LINE_AXIS));
        panel_navbar.add(filler4);

        jLabel7.setIcon(new javax.swing.ImageIcon("src\\main\\java\\com\\mycompany\\gerenciamento\\uniformes\\Images\\logo-IFRO-PNG-branco.png"));
        panel_navbar.add(jLabel7);
        panel_navbar.add(filler1);

        nome_sistema.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nome_sistema.setForeground(new java.awt.Color(255, 255, 255));
        nome_sistema.setText("GERENCIAMENTO DE UNIFORMES ACADÊMICOS");
        panel_navbar.add(nome_sistema);
        panel_navbar.add(filler3);

        btn_nav_Inicio.setBackground(new java.awt.Color(35, 91, 88));
        btn_nav_Inicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nav_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        btn_nav_Inicio.setText("Inicio");
        btn_nav_Inicio.setBorder(null);
        btn_nav_Inicio.setBorderPainted(false);
        btn_nav_Inicio.setContentAreaFilled(false);
        btn_nav_Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nav_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nav_InicioActionPerformed(evt);
            }
        });
        panel_navbar.add(btn_nav_Inicio);
        panel_navbar.add(filler6);

        btn_nav_distribuicao.setBackground(new java.awt.Color(35, 91, 88));
        btn_nav_distribuicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nav_distribuicao.setForeground(new java.awt.Color(255, 255, 255));
        btn_nav_distribuicao.setText("Distribuição");
        btn_nav_distribuicao.setBorder(null);
        btn_nav_distribuicao.setBorderPainted(false);
        btn_nav_distribuicao.setContentAreaFilled(false);
        btn_nav_distribuicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nav_distribuicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nav_distribuicaoActionPerformed(evt);
            }
        });
        panel_navbar.add(btn_nav_distribuicao);
        panel_navbar.add(filler7);

        btn_nav_alunos.setBackground(new java.awt.Color(35, 91, 88));
        btn_nav_alunos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nav_alunos.setForeground(new java.awt.Color(255, 255, 255));
        btn_nav_alunos.setText("Alunos");
        btn_nav_alunos.setBorderPainted(false);
        btn_nav_alunos.setContentAreaFilled(false);
        btn_nav_alunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nav_alunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nav_alunosActionPerformed(evt);
            }
        });
        panel_navbar.add(btn_nav_alunos);

        btn_nav_servidores.setBackground(new java.awt.Color(35, 91, 88));
        btn_nav_servidores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nav_servidores.setForeground(new java.awt.Color(255, 255, 255));
        btn_nav_servidores.setText("Servidores");
        btn_nav_servidores.setBorderPainted(false);
        btn_nav_servidores.setContentAreaFilled(false);
        btn_nav_servidores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nav_servidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nav_servidoresActionPerformed(evt);
            }
        });
        panel_navbar.add(btn_nav_servidores);

        btn_nav_uniformes.setBackground(new java.awt.Color(35, 91, 88));
        btn_nav_uniformes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nav_uniformes.setForeground(new java.awt.Color(255, 255, 255));
        btn_nav_uniformes.setText("Uniformes");
        btn_nav_uniformes.setBorderPainted(false);
        btn_nav_uniformes.setContentAreaFilled(false);
        btn_nav_uniformes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nav_uniformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nav_uniformesActionPerformed(evt);
            }
        });
        panel_navbar.add(btn_nav_uniformes);
        panel_navbar.add(filler5);

        getContentPane().add(panel_navbar, java.awt.BorderLayout.NORTH);

        panel_telaInicial.setBackground(new java.awt.Color(204, 255, 102));
        panel_telaInicial.setPreferredSize(new java.awt.Dimension(1360, 650));
        panel_telaInicial.setLayout(new java.awt.CardLayout());

        Inicio.setBackground(new java.awt.Color(204, 255, 153));

        jLabel1.setText("Inicio");

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(0, 1632, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 1633, Short.MAX_VALUE))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(0, 309, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 309, Short.MAX_VALUE))
        );

        panel_telaInicial.add(Inicio, "inicio");

        Distribuicao.setBackground(new java.awt.Color(255, 255, 255));
        Distribuicao.setMaximumSize(new java.awt.Dimension(1360, 650));
        Distribuicao.setMinimumSize(new java.awt.Dimension(1360, 650));
        Distribuicao.setPreferredSize(new java.awt.Dimension(1360, 650));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Tamanho", "Uniforme", "Matrícula", "Servidor Responsável", "Quantidade", "Data de Troca", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(4, 120, 87));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("+ Cadastrar Distribuição");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel6.setText("Controle de Distribuição");

        jLabel8.setText("Tenha controle em tempo real das distribuições de uniformes.");

        javax.swing.GroupLayout DistribuicaoLayout = new javax.swing.GroupLayout(Distribuicao);
        Distribuicao.setLayout(DistribuicaoLayout);
        DistribuicaoLayout.setHorizontalGroup(
            DistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DistribuicaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(2011, 2011, 2011))
            .addGroup(DistribuicaoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(DistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(DistribuicaoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(665, 665, 665)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DistribuicaoLayout.setVerticalGroup(
            DistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DistribuicaoLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(DistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DistribuicaoLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(42, 42, 42))
        );

        panel_telaInicial.add(Distribuicao, "distribuicao");

        Alunos.setBackground(new java.awt.Color(255, 204, 255));

        jLabel3.setText("Alunos");

        javax.swing.GroupLayout AlunosLayout = new javax.swing.GroupLayout(Alunos);
        Alunos.setLayout(AlunosLayout);
        AlunosLayout.setHorizontalGroup(
            AlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlunosLayout.createSequentialGroup()
                .addContainerGap(2624, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(630, 630, 630))
        );
        AlunosLayout.setVerticalGroup(
            AlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlunosLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel3)
                .addContainerGap(516, Short.MAX_VALUE))
        );

        panel_telaInicial.add(Alunos, "alunos");

        Servidores.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setText("Servidores");

        javax.swing.GroupLayout ServidoresLayout = new javax.swing.GroupLayout(Servidores);
        Servidores.setLayout(ServidoresLayout);
        ServidoresLayout.setHorizontalGroup(
            ServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServidoresLayout.createSequentialGroup()
                .addContainerGap(2598, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(630, 630, 630))
        );
        ServidoresLayout.setVerticalGroup(
            ServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServidoresLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel4)
                .addContainerGap(516, Short.MAX_VALUE))
        );

        panel_telaInicial.add(Servidores, "servidores");

        Uniformes.setBackground(new java.awt.Color(255, 153, 153));

        jLabel5.setText("Uniformes");

        javax.swing.GroupLayout UniformesLayout = new javax.swing.GroupLayout(Uniformes);
        Uniformes.setLayout(UniformesLayout);
        UniformesLayout.setHorizontalGroup(
            UniformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UniformesLayout.createSequentialGroup()
                .addContainerGap(2601, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(630, 630, 630))
        );
        UniformesLayout.setVerticalGroup(
            UniformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UniformesLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel5)
                .addContainerGap(516, Short.MAX_VALUE))
        );

        panel_telaInicial.add(Uniformes, "uniformes");

        getContentPane().add(panel_telaInicial, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nav_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nav_InicioActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panel_telaInicial, "inicio");
        System.out.println("Mostrando painel Inicio");
    }//GEN-LAST:event_btn_nav_InicioActionPerformed

    private void btn_nav_distribuicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nav_distribuicaoActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panel_telaInicial, "distribuicao");
        System.out.println("Mostrando painel Distribuicao");
    }//GEN-LAST:event_btn_nav_distribuicaoActionPerformed

    private void btn_nav_alunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nav_alunosActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panel_telaInicial, "alunos");
        System.out.println("Mostrando painel Alunos");
        //JOptionPane.showMessageDialog(this, "Painel de Alunos ainda não implementado");
    }//GEN-LAST:event_btn_nav_alunosActionPerformed

    private void btn_nav_servidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nav_servidoresActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panel_telaInicial, "servidores");
        System.out.println("Mostrando painel Servidores");
        //JOptionPane.showMessageDialog(this, "Painel de Servidores ainda não implementado");
    }//GEN-LAST:event_btn_nav_servidoresActionPerformed

    private void btn_nav_uniformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nav_uniformesActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panel_telaInicial, "uniformes");
        System.out.println("Mostrando painel Uniformes");
        //JOptionPane.showMessageDialog(this, "Painel de Uniformes ainda não implementado");
    }//GEN-LAST:event_btn_nav_uniformesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alunos;
    private javax.swing.JPanel Distribuicao;
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel Servidores;
    private javax.swing.JPanel Uniformes;
    private javax.swing.JButton btn_nav_Inicio;
    private javax.swing.JButton btn_nav_alunos;
    private javax.swing.JButton btn_nav_distribuicao;
    private javax.swing.JButton btn_nav_servidores;
    private javax.swing.JButton btn_nav_uniformes;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nome_sistema;
    private javax.swing.JPanel panel_navbar;
    private javax.swing.JPanel panel_telaInicial;
    // End of variables declaration//GEN-END:variables
}
