-- MySQL Script generated by MySQL Workbench
-- Sun 08 Jun 2025 09:36:52 PM -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema uniformes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uniformes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uniformes` DEFAULT CHARACTER SET utf8 ;
USE `uniformes` ;

-- -----------------------------------------------------
-- Table `uniformes`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Servidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Servidor` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Servidor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NOT NULL,
  `fk_departamento` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Servidor_Departamento1_idx` (`fk_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_Servidor_Departamento1`
    FOREIGN KEY (`fk_departamento`)
    REFERENCES `uniformes`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Curso` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `n_periodos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `periodo` INT NOT NULL,
  `fk_curso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Aluno_Curso_idx` (`fk_curso` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Curso`
    FOREIGN KEY (`fk_curso`)
    REFERENCES `uniformes`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`TipoUniforme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`TipoUniforme` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`TipoUniforme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Tamanho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Tamanho` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Tamanho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Uniforme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Uniforme` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Uniforme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `fk_tipo_uniforme` INT NOT NULL,
  `fk_tamanho` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Uniforme_TipoUniforme1_idx` (`fk_tipo_uniforme` ASC) VISIBLE,
  INDEX `fk_Uniforme_Tamanho1_idx` (`fk_tamanho` ASC) VISIBLE,
  CONSTRAINT `fk_Uniforme_TipoUniforme1`
    FOREIGN KEY (`fk_tipo_uniforme`)
    REFERENCES `uniformes`.`TipoUniforme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uniforme_Tamanho1`
    FOREIGN KEY (`fk_tamanho`)
    REFERENCES `uniformes`.`Tamanho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Entrega` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_entrega` DATE NOT NULL,
  `semestre` INT NOT NULL,
  `ano` INT NOT NULL,
  `trocado` TINYINT NOT NULL,
  `quantidade` INT NOT NULL,
  `fk_servidor` INT NOT NULL,
  `fk_aluno` INT NOT NULL,
  `fk_uniforme` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Entrega_Servidor1_idx` (`fk_servidor` ASC) VISIBLE,
  INDEX `fk_Entrega_Aluno1_idx` (`fk_aluno` ASC) VISIBLE,
  INDEX `fk_Entrega_Uniforme1_idx` (`fk_uniforme` ASC) VISIBLE,
  CONSTRAINT `fk_Entrega_Servidor1`
    FOREIGN KEY (`fk_servidor`)
    REFERENCES `uniformes`.`Servidor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrega_Aluno1`
    FOREIGN KEY (`fk_aluno`)
    REFERENCES `uniformes`.`Aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrega_Uniforme1`
    FOREIGN KEY (`fk_uniforme`)
    REFERENCES `uniformes`.`Uniforme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Troca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Troca` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Troca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_troca` DATE NOT NULL,
  `fk_entrega_antiga` INT NOT NULL,
  `fk_entrega_nova` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Troca_Entrega2_idx` (`fk_entrega_antiga` ASC) VISIBLE,
  INDEX `fk_Troca_Entrega1_idx` (`fk_entrega_nova` ASC) VISIBLE,
  CONSTRAINT `fk_Troca_Entrega2`
    FOREIGN KEY (`fk_entrega_antiga`)
    REFERENCES `uniformes`.`Entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Troca_Entrega1`
    FOREIGN KEY (`fk_entrega_nova`)
    REFERENCES `uniformes`.`Entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Fornecedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniformes`.`Entradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniformes`.`Entradas` ;

CREATE TABLE IF NOT EXISTS `uniformes`.`Entradas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_entrada` DATE NOT NULL,
  `quantidade` INT NOT NULL,
  `fk_fornecedor` INT NOT NULL,
  `fk_uniforme` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Entradas_Fornecedor1_idx` (`fk_fornecedor` ASC) VISIBLE,
  INDEX `fk_Entradas_Uniforme1_idx` (`fk_uniforme` ASC) VISIBLE,
  CONSTRAINT `fk_Entradas_Fornecedor1`
    FOREIGN KEY (`fk_fornecedor`)
    REFERENCES `uniformes`.`Fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entradas_Uniforme1`
    FOREIGN KEY (`fk_uniforme`)
    REFERENCES `uniformes`.`Uniforme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- INICIO TRIGGERS
DROP TRIGGER IF EXISTS Tgr_Insert_Troca;
DROP TRIGGER IF EXISTS Tgr_Insert_Entrada;
DROP TRIGGER IF EXISTS Tgr_Insert_Entrega;

DELIMITER //
-- Ao cadastrar entrega, subtrair de uniformes a quantidade da entrega.
CREATE TRIGGER Tgr_Insert_Entrega BEFORE INSERT
ON Entrega
FOR EACH ROW 
BEGIN
	UPDATE Uniforme AS u
    SET u.quantidade = u.quantidade - NEW.quantidade
	WHERE u.id = NEW.fk_uniforme;
END;
//
-- Ao cadastrar entrada, adicionar em uniformes a quantidade da entrada.
CREATE TRIGGER Tgr_Insert_Entrada AFTER INSERT
ON Entradas 
FOR EACH ROW
BEGIN 
	UPDATE Uniforme AS u
    SET u.quantidade = u.quantidade + NEW.quantidade
    WHERE u.id = NEW.fk_uniforme;
END;
//
-- Ao cadastrar troca, adicionar em uniformes a quantidade da entrega antiga.
CREATE TRIGGER Tgr_Insert_Troca AFTER INSERT
ON Troca
FOR EACH ROW
BEGIN
	UPDATE Uniforme AS u
    SET u.quantidade = u.quantidade + (SELECT e.quantidade FROM Entrega AS e WHERE e.id = NEW.fk_entrega_antiga)
    WHERE u.id = (SELECT e.fk_uniforme FROM Entrega AS e WHERE e.id = NEW.fk_entrega_antiga);
    
    UPDATE Entrega AS e
    SET e.trocado = 1
    WHERE e.id = NEW.fk_entrega_antiga;
END;
//
DELIMITER ;
-- FIM TRIGGERS

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
